// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package database

import (
	"context"
)

const addPost = `-- name: AddPost :one
;

INSERT INTO posts (user_id, language_id, code, comment, post_date)
   VALUES (?, ?, ?, ?, ?) RETURNING post_id, user_id, language_id, code, comment, post_date
`

type AddPostParams struct {
	UserID     int64
	LanguageID int64
	Code       string
	Comment    string
	PostDate   string
}

func (q *Queries) AddPost(ctx context.Context, arg AddPostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, addPost,
		arg.UserID,
		arg.LanguageID,
		arg.Code,
		arg.Comment,
		arg.PostDate,
	)
	var i Post
	err := row.Scan(
		&i.PostID,
		&i.UserID,
		&i.LanguageID,
		&i.Code,
		&i.Comment,
		&i.PostDate,
	)
	return i, err
}

const addPostIntoTree = `-- name: AddPostIntoTree :one
;

INSERT INTO posts_tree (post_id, parent_post_id)
   VALUES (?, ?) RETURNING post_id, parent_post_id
`

type AddPostIntoTreeParams struct {
	PostID       int64
	ParentPostID int64
}

func (q *Queries) AddPostIntoTree(ctx context.Context, arg AddPostIntoTreeParams) (PostsTree, error) {
	row := q.db.QueryRowContext(ctx, addPostIntoTree, arg.PostID, arg.ParentPostID)
	var i PostsTree
	err := row.Scan(&i.PostID, &i.ParentPostID)
	return i, err
}

const addUser = `-- name: AddUser :one
;

INSERT INTO users (username, password, email, status) VALUES (?, ?, ?, ?)
RETURNING user_id, username, password, email, status
`

type AddUserParams struct {
	Username string
	Password string
	Email    string
	Status   int64
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, addUser,
		arg.Username,
		arg.Password,
		arg.Email,
		arg.Status,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Password,
		&i.Email,
		&i.Status,
	)
	return i, err
}

const getPostsFromRoot = `-- name: GetPostsFromRoot :many
;

SELECT t.post_id, parent_post_id, p.post_id, p.user_id, language_id, code, comment, post_date, u.user_id, username, password, email, status FROM posts_tree t 
  INNER JOIN posts p ON t.post_id = p.post_id 
  INNER JOIN users u ON u.user_id = p.user_id
  WHERE t.post_id = ? OR t.parent_post_id = ?
  ORDER BY t.parent_post_id ASC
`

type GetPostsFromRootParams struct {
	PostID       int64
	ParentPostID int64
}

type GetPostsFromRootRow struct {
	PostID       int64
	ParentPostID int64
	PostID_2     int64
	UserID       int64
	LanguageID   int64
	Code         string
	Comment      string
	PostDate     string
	UserID_2     int64
	Username     string
	Password     string
	Email        string
	Status       int64
}

func (q *Queries) GetPostsFromRoot(ctx context.Context, arg GetPostsFromRootParams) ([]GetPostsFromRootRow, error) {
	rows, err := q.db.QueryContext(ctx, getPostsFromRoot, arg.PostID, arg.ParentPostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostsFromRootRow
	for rows.Next() {
		var i GetPostsFromRootRow
		if err := rows.Scan(
			&i.PostID,
			&i.ParentPostID,
			&i.PostID_2,
			&i.UserID,
			&i.LanguageID,
			&i.Code,
			&i.Comment,
			&i.PostDate,
			&i.UserID_2,
			&i.Username,
			&i.Password,
			&i.Email,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentPosts = `-- name: GetRecentPosts :many
;
  /* Later on, the post should also return the user info (username, user_id) */
  /* INNER JOIN users u ON u.user_id = p.user_id */

SELECT t.post_id, parent_post_id, p.post_id, p.user_id, language_id, code, comment, post_date, u.user_id, username, password, email, status FROM posts_tree t 
  INNER JOIN posts p ON t.post_id = p.post_id 
  INNER JOIN users u ON u.user_id = p.user_id
  WHERE t.parent_post_id = -1
  ORDER BY p.post_id DESC 
  LIMIT 20
`

type GetRecentPostsRow struct {
	PostID       int64
	ParentPostID int64
	PostID_2     int64
	UserID       int64
	LanguageID   int64
	Code         string
	Comment      string
	PostDate     string
	UserID_2     int64
	Username     string
	Password     string
	Email        string
	Status       int64
}

func (q *Queries) GetRecentPosts(ctx context.Context) ([]GetRecentPostsRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecentPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentPostsRow
	for rows.Next() {
		var i GetRecentPostsRow
		if err := rows.Scan(
			&i.PostID,
			&i.ParentPostID,
			&i.PostID_2,
			&i.UserID,
			&i.LanguageID,
			&i.Code,
			&i.Comment,
			&i.PostDate,
			&i.UserID_2,
			&i.Username,
			&i.Password,
			&i.Email,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsers = `-- name: GetUsers :many
SELECT user_id, username, password, email, status FROM users
`

func (q *Queries) GetUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.Password,
			&i.Email,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loginUser = `-- name: LoginUser :one
;

SELECT user_id, username, password, email, status FROM users 
  WHERE username = ? AND password = ? 
  LIMIT 1
`

type LoginUserParams struct {
	Username string
	Password string
}

func (q *Queries) LoginUser(ctx context.Context, arg LoginUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, loginUser, arg.Username, arg.Password)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Password,
		&i.Email,
		&i.Status,
	)
	return i, err
}

const searchPosts = `-- name: SearchPosts :many
;

SELECT found_post_id, post_id, p.user_id, language_id, code, comment, post_date, u.user_id, username, password, email, status 
  FROM (
    SELECT
      CASE parent_post_id
      WHEN -1 THEN post_id
      ELSE parent_post_id
      END found_post_id
    FROM posts_tree
    GROUP BY found_post_id
  ) t
  INNER JOIN posts p ON p.post_id = t.found_post_id
  INNER JOIN users u ON u.user_id = p.user_id
  WHERE p.code LIKE ? OR p.comment LIKE ?
  ORDER BY t.found_post_id DESC 
  LIMIT 20
`

type SearchPostsParams struct {
	Code    string
	Comment string
}

type SearchPostsRow struct {
	FoundPostID interface{}
	PostID      int64
	UserID      int64
	LanguageID  int64
	Code        string
	Comment     string
	PostDate    string
	UserID_2    int64
	Username    string
	Password    string
	Email       string
	Status      int64
}

func (q *Queries) SearchPosts(ctx context.Context, arg SearchPostsParams) ([]SearchPostsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchPosts, arg.Code, arg.Comment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPostsRow
	for rows.Next() {
		var i SearchPostsRow
		if err := rows.Scan(
			&i.FoundPostID,
			&i.PostID,
			&i.UserID,
			&i.LanguageID,
			&i.Code,
			&i.Comment,
			&i.PostDate,
			&i.UserID_2,
			&i.Username,
			&i.Password,
			&i.Email,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
